server:
  port: 9003

eureka:
  instance:
    hostname: eureka03.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka01.com:9001/eureka/,http://eureka02.com:9002/eureka/
