server:
  port: 9300


spring:
  application:
    name: zuul-gateway

eureka:
  instance:
    instance-id: myzuul.com
    prefer-ip-address: true
  client:
    serviceUrl:
#      defaultZone: http://localhost:9001/eureka
      defaultZone: http://eureka01.com:9001/eureka/,http://eureka02.com:9002/eureka/,http://eureka03.com:9003/eureka/

#zuul:
#  prefix: lantrack
#  ignored-services: *
#  routes:
#    provider: /pro/**
#
