server:
  port: 9101

spring:
  application:
    name: provider

eureka:
  instance:
    instance-id: provider-hystrix
    prefer-ip-address: true
  client:
    serviceUrl:
#      defaultZone: http://localhost:9001/eureka
      defaultZone: http://eureka01.com:9001/eureka/,http://eureka02.com:9002/eureka/,http://eureka03.com:9003/eureka/

info:
  name: provider
  company: www.lantrack.net
