server:
  port: 9201
spring:
  application:
    name: consumer

eureka:
  instance:
    instance-id: consumer02
    prefer-ip-address: true
  client:
    serviceUrl:
      #  defaultZone: http://localhost:9001/eureka
      defaultZone: http://eureka01.com:9001/eureka/,http://eureka02.com:9002/eureka/,http://eureka03.com:9003/eureka/


info:
  name: consumer
  company: www.lantrack.net
